# This file is required by our CI/CD pipeline defined within AWS CodePipeline
# and manages how the build and deployment are processed.
version: 0.2

phases:
  install:
    commands:
      - echo Copying settings.xml file...
      - cp ./settings.xml /root/.m2/settings.xml
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/udccs-poc-*.jar